config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'news#index'
  resources :news do
    patch 'change_status', on: :member
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.user?
      can [:index, :show, :stats], News
    else
      can [:index, :show], News
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  has_many :newsusers
  has_many :users, through: :newsusers

  validates :author, presence: true, length: { minimum: 3 }
  validates :text, presence: true, length: { minimum: 15 }
end

app/models/newsuser.rb
class Newsuser < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: { user: 0, admin: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :newsusers
  has_many :news, through: :newsusers

  def read?(news)
    newsuser = self.newsusers.find_by(news_id: news)
    newsuser && newsuser.read ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @newslist = News.all
    if params[:commit]
      @newslist = Services::NewsSearcher.new(current_user, params).search
    end

    prepare_data
    respond_to do |format|
      format.json { render json: { newslist: @newslist,
                                   can_add: (can? :add, News),
                                   can_stats: (can? :stats, News) } }
      format.html {}
    end
  end

  def new
    redirect_to root_path unless can? :manage, News
    @new_news = News.new
  end

  def create
    redirect_to root_path unless can? :manage, News
    news = News.new(news_params)
    respond_to do |format|
      if news.save
        flash[:success] = t('flash_messages.create.success', resource: @news)
        format.json { render json: news }
        format.html {}
      else
        flash[:error] = t('flash_messages.create.failure', resource: @news)
        @news = news
        render :new
      end
    end
  end

  def change_status
    newsuser = current_user.newsusers.find_by(news_id: params[:id])
    if newsuser.nil?
      newsuser = current_user.newsusers.create(news_id: params[:id], read: true)
      newsuser.save
    else
      newsuser.read ^= true
      newsuser.save
    end
    respond_to do |format|
      format.json { render json: { status: newsuser.read ? newsuser : false } }
    end
  end

  private

  def news_params
    params.require(:news).permit(:author, :text)
  end

  def prepare_data
    @newslist = @newslist.map do |news|
      {
        news: news,
        status:
          if (can? :stats, News) && current_user.read?(news)
            Newsuser.find_by(user_id: current_user, news_id: news)
          else
            false
          end
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title
      = content_for(:title) ? yield(:title) : "Newslist"
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    header.navigation
      .nav-left
        = link_to News, '/'
      .nav-right
        - if current_user
          = link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          = link_to 'Sign in', new_user_session_path

    - unless flash.blank?
      - flash.each do |name, msg|
        - classname_end = ''
        - case name
        - when 'notice' then classname_end += 'success'
        - when 'alert' then classname_end += 'danger'
        - when 'warning' then classname_end += 'warning'
        - else classname_end += 'info'
        - classname = 'alert alert-' + classname_end
        = content_tag :div, msg, class: classname, role: 'alert'

    = yield

app/views/news/_new.slim
.modal-dialog.modal-content.modal-body
  h1.modal-header Add
  = simple_form_for news, remote: true do |f|
      = f.input :author, label: 'Author'
      = f.input :text, label: 'News text'
      = f.button :submit, class: 'create_new btn-primary'

app/views/news/_news.slim
article
  p.author = news.author
  p.newstext = news.text
  time.pubdate = news.created_at
  - if current_user
    - if current_user.read?(current_user, news)
      = link_to 'Unread', change_status_news_path(news), class: 'btn btn-danger', method: 'patch'
    - else
      = link_to 'Read', change_status_news_path(news), class: 'btn btn-primary', method: 'patch'

app/views/news/_statistics.slim
aside.statistics
  h2 Statistics
  section
    p Total news:
    = total
  section
    p Readed news:
    = total_readed
  section
    p Today's news:
    = today
  section
    p Today's readed news:
    = readed_today

app/views/news/index.slim
= react_component 'List', { newslist: @newslist, can_stats: (can? :stats, News), can_add: (can? :add, News) }

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>